### ISSUE TITLE
Feature request: flags to specify inventory file and vault password file at the command line

### ISSUE THREAD

**Issue by bwlz** [dellis23/ansible-toolkit#1]
I personally have several different inventory files across multiple ansible environments - it would be awesome if I could specify for example:

     atk-show-vars -i ~/ansible/hosts hostname

A similar flag to specify the vault password file would be nice for folks who may have multiple vault password files.

**Comment by dellis23** [comment]
This should be available now @bwlz .  Thanks for reporting!

**Comment by bwlz** [comment]
You rock, thanks!
