### ISSUE TITLE
travis-ci.org integration

### ISSUE THREAD

**Issue by steenzout** [dellis23/ansible-toolkit#27]
@dellis23 can you please login at travis-ci.org and setup this repo to have tests run there, please?

thank you!

**Comment by dellis23** [comment]
@steenzout I've added the repo to travis but I'm not sure what additional steps I need to do.  It says we just need to add a `travis.yml` file now.  I'm assuming you know what to do from here?

**Comment by steenzout** [comment]
yes.

thank you!
