### ISSUE TITLE
integrate with coveralls.io

### ISSUE THREAD

**Issue by steenzout** [dellis23/ansible-toolkit#35]

**Comment by steenzout** [comment]
@dellis23 can you please go to coveralls.io and add this repo there, please? thank you!

**Comment by dellis23** [comment]
@steenzout Sorry about that, I've been meaning to get to this.  Do you still want it added?

**Comment by steenzout** [comment]
@dellis23 actually I do...

**Comment by dellis23** [comment]
I _think_ I did it right.

**Comment by steenzout** [comment]
worked.
