### ISSUE TITLE
integrate with requires.io

### ISSUE THREAD

**Issue by steenzout** [dellis23/ansible-toolkit#36]

**Comment by steenzout** [comment]
@dellis23 this one as well...

**Comment by dellis23** [comment]
Should be done.  Please verify.

**Comment by steenzout** [comment]
worked: https://requires.io/github/dellis23/ansible-toolkit/requirements/?branch=master

**Comment by bsacks99** [comment]
Unsubscribe 

~B

Typos courtesy of my iPhone
