### ISSUE TITLE
integrate with landscape.io

### ISSUE THREAD

**Issue by steenzout** [dellis23/ansible-toolkit#37]

**Comment by steenzout** [comment]
@dellis23 can you please go to landscape.io and add this repo there? thank you!

**Comment by dellis23** [comment]
@steenzout Sorry about that, I've been meaning to get to this.  Do you still want it added?

**Comment by steenzout** [comment]
@dellis23 same for this.
I got the info I needed but it's not enough to get the badge right.

**Comment by dellis23** [comment]
I think this is done now.  Please verify.

**Comment by steenzout** [comment]
worked: https://landscape.io/github/dellis23/ansible-toolkit.
