### ISSUE TITLE
atk-show-vars for playbooks

### ISSUE THREAD

**Issue by rndmh3ro** [dellis23/ansible-toolkit#8]
Similar like in #4, there should be an option to show all variables affecting a host when running a playbook. This in turn should of course include all roles used in the playbook.
E.g. like that:

```
 atk-show-vars host playbook.yml
```

**Comment by dellis23** [comment]
Thanks for the feedback.  I'm anticipating these are going to be quite a bit more complex since roles can set facts based on the output of other commands, so I'm going to have to ponder a bit how to do this without it getting unmanageable.
